/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "error-dim": "#67040d",
        "outline": "#717d7a",
        "on-primary": "#e7ffed",
        "on-secondary-fixed": "#21425c",
        "on-error-container": "#6e0a12",
        "primary-container": "#a2f4c4",
        "outline-variant": "#a8b5b0",
        "on-secondary-container": "#355570",
        "tertiary-fixed-dim": "#efcbab",
        "primary-dim": "#00603c",
        "surface": "#f5faf7",
        "on-primary-container": "#005e3b",
        "secondary": "#43627e",
        "on-background": "#293532",
        "primary": "#156c47",
        "on-tertiary-fixed-variant": "#6f553b",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#3f5e7a",
        "background": "#f5faf7",
        "secondary-container": "#cde5ff",
        "on-tertiary-fixed": "#503921",
        "primary-fixed-dim": "#94e5b7",
        "surface-bright": "#f5faf7",
        "surface-tint": "#156c47",
        "tertiary-dim": "#684e35",
        "secondary-fixed": "#cde5ff",
        "on-tertiary-container": "#644b32",
        "on-secondary": "#f6f9ff",
        "on-primary-fixed-variant": "#0f6944",
        "secondary-fixed-dim": "#b8d8f8",
        "surface-container-highest": "#d9e5e1",
        "surface-container-high": "#e0eae6",
        "error": "#a83836",
        "tertiary-fixed": "#fed9b8",
        "inverse-primary": "#abfdcc",
        "tertiary": "#755a40",
        "surface-container": "#e7f0ec",
        "primary-fixed": "#a2f4c4",
        "inverse-on-surface": "#999e9c",
        "error-container": "#fa746f",
        "surface-dim": "#d0ddd8",
        "secondary-dim": "#365671",
        "tertiary-container": "#fed9b8",
        "on-tertiary": "#fff7f4",
        "on-surface": "#293532",
        "surface-variant": "#d9e5e1",
        "inverse-surface": "#0a0f0e",
        "on-primary-fixed": "#00492d",
        "on-error": "#fff7f6",
        "on-surface-variant": "#56625e",
        "surface-container-low": "#eef5f2"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["'Plus Jakarta Sans'", "sans-serif"],
        "body": ["'Be Vietnam Pro'", "sans-serif"],
        "label": ["'Be Vietnam Pro'", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/container-queries'),
  ],
};
